using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace SurfaceApplication1
{
    /**
     * This class represents a SearchResult, which has text, a tag, folio, etc.
     * Lists of SearchResults are generated by many of the search methods in Search.cs.
     * Many elements of SearchResults are then transferred to ResultBoxItems for result display in convertSearchResultToResultBoxItem() from SearchTab.cs.
     * Primary Coder: Alison Y. Chang
     * */
    public class SearchResult
    {
        public double matchStrength; // Used to indicate how strongly the result matches the search specifications
        public Image thumbnail, minithumbnail;
        public int lineNum, resultType; // 1 = poetry, 2 = music, 3 = image
        public List<SpecialString> excerpts = new List<SpecialString>();
        public Point topL, bottomR;
        public String folio, text1, text2, tag, lineRange;


        
        public SearchResult()
        {



        }
    }
}
